# Tensors, Predictions and Language Models

In this notebook, we'll explore the fundamental concepts of AI, from numbers and tensors to how language models work.

## 1. Numbers and Tensors

In AI, everything ultimately comes down to numbers. An image, a sentence, or audio might seem very different to us, but to an AI model, they're just collections of numbers.

A key part of AI is **Machine Learning**: a subset of artificial intelligence used to recognize patterns and solve problems, such as natural language processing (text processing).

In [1]:
# In Python, we can work with lists
example_list = [1, 2, 3, 4, 5]
print("Python list:", example_list)
print("Type:", type(example_list))

Python list: [1, 2, 3, 4, 5]
Type: <class 'list'>


## 2. What are Tensors?

In machine learning and deep learning, all data is ultimately stored as numbers. To efficiently organize and process these numbers, we use **tensors**.

A tensor is best thought of as a **multi-dimensional array** - an extension of things you already know:
- A single number (e.g., 5) is a tensor of dimension 0
- A list (e.g., [1,2,3]) is a tensor of dimension 1
- A table (matrix) is a tensor of dimension 2
- Higher dimensions occur when you store multiple images at once

In [2]:
#!pip install numpy
import numpy as np

# Tensor rank 0: scalar
scalar = np.array(5)
print("Rank 0 (scalar):", scalar)

# Tensor rank 1: vector
vector = np.array([1, 2, 3, 4, 5])
print("\nRank 1 (vector):", vector)

# Tensor rank 2: matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("\nRank 2 (matrix):\n", matrix)

Rank 0 (scalar): 5

Rank 1 (vector): [1 2 3 4 5]

Rank 2 (matrix):
 [[1 2 3]
 [4 5 6]]


## 3. Shape of a Tensor

The **shape** of a tensor describes how the data is organized. It tells you how many elements exist in each dimension.

In [3]:
# Understanding shape
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("Matrix:")
print(matrix)
print("\nShape:", matrix.shape)
print("Interpretation: 2 rows and 3 columns")

Matrix:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Interpretation: 2 rows and 3 columns


## 4. Rank (Number of Dimensions)

The **rank** of a tensor is the number of dimensions it has. It shows how "complex" the structure is:
- Rank 0: scalar (one value)
- Rank 1: vector (list)
- Rank 2: matrix (table)
- Rank 3+: higher dimensions

In [4]:
# Comparing rank and shape
scalar = np.array(5)
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar - Rank:", scalar.ndim, ", Shape:", scalar.shape)
print("Vector - Rank:", vector.ndim, ", Shape:", vector.shape)
print("Matrix - Rank:", matrix.ndim, ", Shape:", matrix.shape)
print("3D Tensor - Rank:", tensor_3d.ndim, ", Shape:", tensor_3d.shape)

Scalar - Rank: 0 , Shape: ()
Vector - Rank: 1 , Shape: (3,)
Matrix - Rank: 2 , Shape: (2, 3)
3D Tensor - Rank: 3 , Shape: (2, 2, 2)


## 5. Size of a Tensor

The **size** of a tensor is the total number of elements. Calculate it by multiplying all dimensions together.

In [5]:
# Calculating tensor size
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("Matrix shape:", matrix.shape)
print("Total size: 2 × 3 =", matrix.size)

tensor_3d = np.random.rand(3, 4, 2)
print("\n3D Tensor shape:", tensor_3d.shape)
print("Total size: 3 × 4 × 2 =", tensor_3d.size)

Matrix shape: (2, 3)
Total size: 2 × 3 = 6

3D Tensor shape: (3, 4, 2)
Total size: 3 × 4 × 2 = 24


## 6. Introduction to PyTorch (`torch`)

PyTorch is a popular library for working with tensors and building machine learning models.

At the most basic level, you can use it to:
- create tensors
- do math on them
- reshape them
- generate random data

A tensor in PyTorch is very similar to a NumPy array, but PyTorch is designed to work well for deep learning.

### Tiny examples

- `torch.tensor(...)` creates a tensor
- `+`, `*`, and `@` work as expected (@ means matrix multiplication, this is an advanced topic: https://en.wikipedia.org/wiki/Matrix_multiplication)
- `.shape` shows the dimensions
- `.reshape(...)` changes the layout of the data

In [6]:
!pip install torch
import torch

# Create a tensor
x = torch.tensor([1, 2, 3])
print(x)

# Add a scalar
y = x + 2
print(y)

# Multiply tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a * b)

# Check shape
m = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(m.shape)

# Reshape a tensor
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v.reshape(2, 3))


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


tensor([1, 2, 3])
tensor([3, 4, 5])
tensor([ 4, 10, 18])
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### What you will practice

- Creating tensors
- Doing basic arithmetic
- Checking tensor shapes
- Reshaping data


### Exercises

1. Create a tensor with the numbers 1 to 5.
2. Multiply a tensor by 2.
3. Create a 2×3 tensor and print its shape.
4. Add two tensors together.
5. Try reshaping a tensor from shape `(6,)` to `(2, 3)`. 

#### Exercise 1: Create a tensor with the numbers 1 to 5

In [7]:
#TODO: Create a tensor with the numbers 1 to 5
import torch
t1 = torch.tensor([1,2,3,4,5])
print(t1)

tensor([1, 2, 3, 4, 5])


#### Check your work with this test:

In [8]:
assert torch.equal(t1, torch.tensor([1, 2, 3, 4, 5]))
assert t1.shape == (5,)

#### Exercise 2: Multiply a tensor by 2

In [9]:
#TODO: Multiply the tensor by 2
t2 = torch.tensor([1,2,3,4,5])
t2 = t2 * 2
print(t2)

assert torch.equal(t2, torch.tensor([2, 4, 6, 8, 10]))
assert t2.shape == (5,)



tensor([ 2,  4,  6,  8, 10])


#### Exercise 3: Create a 2×3 tensor and print its shape

In [10]:
#TODO Create a 2×3 tensor and print its shape
t3 = torch.tensor([[1,2,3],
                  [4,5,6]])
print(t3.shape)

assert t3.shape == (2, 3)

torch.Size([2, 3])


#### Exercise 4: Add two tensors together

In [11]:
#TODO: Add two tensors together

a = torch.tensor([1,2,3]) # first tensor
b = torch.tensor([4,5,6]) # second tensor

t4 = a + b
print(t4)

assert torch.equal(t4, torch.tensor([5, 7, 9]))
assert t4.shape == (3,)

tensor([5, 7, 9])


#### Exercise 5: reshape a tensor from (6,) to (2, 3)

In [12]:
#TODO: reshape a tensor from (6,) to (2, 3)
t5 = torch.tensor([1,2,3,4,5,6])
t5_reshaped = torch.tensor([[1,2,3],[4,5,6]])


assert t5.shape == (6,)
assert t5_reshaped.shape == (2, 3)
assert torch.equal(t5_reshaped, torch.tensor([[1, 2, 3],
                                              [4, 5, 6]]))

#### RETURN TO PDF FOR FURTHER EXERCISES

# Section 2: predictions

## Making and Improving Predictions

A model starts by making a **prediction** and comparing it to the **true value**.  
The difference is measured with a loss function.

Example target rule:

**output** = 2 × **input**

Suppose:
- input = 2
- true output = 4

If the model currently guesses **output** = 1 × **input**, then:

**ŷ** = 1 × 2 = 2

Using squared error:

**loss** = (ŷ - y)² = (2 - 4)² = 4

---

## Goal: Minimize the Loss

Training tries to make this loss as small as possible by updating model parameters.

---

## Gradient Descent (Intuition)

Gradient descent is a step-by-step optimization method:

1. Compute the slope (gradient) of the loss.
2. Move a small step in the opposite direction.
3. Repeat.

Update rule:

**x_new** = **x** - α · **f'**(**x**)

where α is the learning rate.

---

## Example: Minimize **f(x) = x²**

- **f'**(**x**) = 2**x**
- Start at **x = 3**, α = 0.1

Step 1:

**x** = 3 - 0.1 · 6 = 2.4

Step 2:

**x** = 2.4 - 0.1 · 4.8 = 1.92

So **x** moves toward 0, the minimum of **x²**.

---

## Reflection Questions

- Why do steps get smaller near **x = 0**?
- What happens if the learning rate is too large?
- What happens if it is too small?

Now continue with the code cells to implement this process.


### YOUR ANSWER HERE:

#### Exercise 1: define a quadratic function and its derivative 

In [16]:
def f(x):
    x = 3.0
    return x**2

def grad_f(x):
    x = 3.0
    return x*2
    

assert f(3.0) == 9.0
assert grad_f(3.0) == 6.0

#### Exercise 2: One step of gradient descent to minimize the function

define a function to perform one step of gradient descent:

Remember the update rule: **x_new** = **x** - α · **f'**(**x**)

In [ ]:
def gd_step(x, lr):
    gradient = x*2
    return x - lr * gradient



# DO NOT EDIT BELOW THIS LINE
x0 = 4.0  
lr = 0.1
x1 = gd_step(x0, lr)

assert np.isclose(x1, 3.2)
#assert f(x1) < f(x0)

-15.200000000000003


AssertionError: 

#### Exercise 3: setup a loop to perform multiple steps of gradient descent and observe the results

in this exercise, you will implement a loop to perform multiple steps of gradient descent and observe how the value of **x** changes over time.

HINT: you can use a `for` loop to repeat the gradient descent step multiple times, and print the value of **x** at each step to see how it evolves.

In [ ]:
def run_gd(x0, lr, steps):
    x = x0
    xs = [x]
    # TODO: implement a loop to perform multiple steps of gradient descent
    for ...

    return ...

xs = run_gd(x0=5.0, lr=0.1, steps=20)
assert abs(xs[-1]) < abs(xs[0])
assert f(xs[-1]) < f(xs[0])

#### Exercise 4: Experiment with different learning rates and observe the effects on convergence.

in this exercise, you will try different learning rates (α) and observe how they affect the convergence of the gradient descent process.

try to visualize the results by plotting the value of **x** over time for different learning rates. You can use libraries like `matplotlib` to create these plots.

Use the function (plot_gradient_descent) and give the parameter lr as your learning rate. define below to run your gradient descent loop and visualize the results.

In [ ]:
import matplotlib.pyplot as plt

def plot_gradient_descent(lr, steps=20):
    x = x0  # uses existing x0 from the notebook
    xs = [x]

    # Gradient descent updates
    for _ in range(steps):
        x = x - lr * grad_f(x)
        xs.append(x)

    xs = np.array(xs)
    ys = f(xs)

    # Set fixed bounds for the quadratic function
    x_curve = np.linspace(-4, 4, 400)
    y_curve = f(x_curve)

    plt.figure(figsize=(9, 5))
    plt.plot(x_curve, y_curve, label="f(x) = x²", color="steelblue")
    plt.plot(xs, ys, "o-", color="crimson", label="Gradient descent steps")

    # Mark argmin
    plt.scatter([0], [0], color="green", s=80, zorder=5, label="argmin = 0")

    # Optional arrows to show direction of steps
    for i in range(len(xs) - 1):
        plt.annotate(
            "",
            xy=(xs[i + 1], ys[i + 1]),
            xytext=(xs[i], ys[i]),
            arrowprops=dict(arrowstyle="->", color="gray", lw=1),
        )

    plt.title(f"Gradient Descent on f(x)=x² (lr={lr})")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.xlim(-4, 4)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    return xs


In [ ]:
# YOUR CODE HERE

# Question: 

- What happens if you set the learning rate to a very high value (e.g., lr = 1.0)? Try it out and observe the results.

#### YOUR ANSWER HERE

# Section 3: Language Models

In this section, we will explore language models and how they can be used to predict the next word in a sentence. We will do this in two ways:

1. with a small pretrained model from Hugging Face; this is a popular library that provides access to many pretrained language models that you can use for various natural language processing tasks.
2. with a handmade mini language model table, so you can also show the idea behind next-word prediction without extra training.



## 1. Load a Pretrained Language Model

We load a small pretrained causal language model and its tokenizer. This model is already trained and can be used immediately for text completion.

A **causal language model** predicts the next token in a sequence from left to right, based on previous tokens. Think of it as reading a sentence word by word and estimating what comes next—just like the exercises in the PDF.

In [ ]:
# this install may take a while, but it only needs to be done once. after that, you can comment it out
#%pip install transformers
import torch
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(model_name).to(device)
model.eval()

print("Device:", device)
print("Model loaded:", model_name)
print("Vocabulary size:", tokenizer.vocab_size)

Some tests to check if the model is working:

In [ ]:
# Test the model and tokenizer
test_text = "Hello, how are"
inputs = tokenizer(test_text, return_tensors="pt").to(device)
print("\nTest tokenization:")
print(f"Input text: '{test_text}'")
print(f"Token IDs: {inputs['input_ids']}")
print(f"Tokens: {tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])}")

# Generate next token prediction
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
    next_token_logits = logits[0, -1, :]
    next_token_id = next_token_logits.argmax().item()
    next_token = tokenizer.decode([next_token_id])
    print(f"\nPredicted next token: '{next_token}'")

## Tokenize a prompt: 

We take a short prompt and convert it into tokens that the model can understand. This is done using the tokenizer associated with the pretrained model. The tokenizer breaks down the input text into smaller pieces (tokens) and converts them into numerical format that the model can process. Think of this as translating human language into a format that the AI can understand and work with. Like how we break down sentences into words and letters to understand them better, the tokenizer does something similar for the AI model.

In [ ]:
prompt = "He was a large, heavy man with a very big"

encoded = tokenizer(prompt, return_tensors="pt")
input_ids = encoded["input_ids"].to(device)
attention_mask = encoded["attention_mask"].to(device)

tokens = tokenizer.convert_ids_to_tokens(input_ids[0].tolist())

print("Prompt:")
print(prompt)
print()
print("Token ids:")
print(input_ids[0].tolist())
print()
print("Tokens:")
print(tokens)

You may notice that model tokens can be confusing to read. Still, they are the building blocks the model uses to understand and generate text.

Each token corresponds to a piece of input text, and the model uses token sequences to predict what comes next. As you try different prompts, notice how the model's predictions change with context.

Try a few prompts and compare the results.

# 3. Predict the Next Token

Next, we give the model a prompt and let it predict the next token.

This is the core idea behind language models: they read a sequence of tokens and estimate what comes next based on patterns learned during training. Different prompts produce different probability distributions and therefore different continuations.

In [ ]:
with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
    next_token_logits = outputs.logits[0, -1, :]
    next_token_probs = torch.softmax(next_token_logits, dim=-1)

top_k = 10
top_probs, top_ids = torch.topk(next_token_probs, k=top_k)

top_tokens = tokenizer.convert_ids_to_tokens(top_ids.tolist())
top_words = [tokenizer.decode([tid]) for tid in top_ids.tolist()]

print(f"Top next-token predictions for the sentence '{prompt}...':")
for rank, (tok, word, prob) in enumerate(zip(top_tokens, top_words, top_probs.tolist()), start=1):
    print(f"{rank:>2}. token={tok:<15} text={word!r:<18} prob={prob:.4f}")

Sometimes two or more next tokens have very similar probabilities. In that case, there may not be one clearly "best" continuation.

This is normal in language modeling: natural language is often ambiguous, and multiple continuations can be valid in context.

A useful metric here is **perplexity**. Perplexity measures how well a model predicts a sequence, and is defined as:

$$
\text{Perplexity} = \exp\left(\text{average negative log-likelihood}\right)
$$

- Lower perplexity means the model assigns higher probability to the true next tokens.
- Higher perplexity means the model is more "surprised" by the text.
- Perplexity values should only be compared on the same dataset and tokenization setup.

So, ambiguity is a property of language/context, while perplexity is a quantitative model-evaluation metric.

# Generate a short text continuation

Here we will use the model to generate a short continuation of the input prompt. This allows us to see how the model can take a given piece of text and extend it in a coherent way, based on the patterns it has learned during training. By providing different prompts, you can observe how the model generates different continuations, demonstrating its ability to understand context and produce relevant text. Try it out and see how the model responds to different prompts!

Do note that the generated text will not always be perfect or factual at all. Longer continuations can often lead to more errors, as the model may lose track of the original context or introduce irrelevant information. It's important to keep in mind that language models are not perfect and can sometimes produce outputs that are nonsensical or factually incorrect, especially as the length of the generated text increases. Always critically evaluate the output and consider the limitations of the model when using it for text generation tasks!

In [ ]:
generated_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=20, # CHANGE THIS TO GENERATE MORE OR LESS TEXT
    do_sample=True,
    pad_token_id=tokenizer.eos_token_id,
)

generated_text = tokenizer.decode(generated_ids[0], skip_special_tokens=True)

print("Generated continuation:")
print(generated_text)

You can experiment with different prompts and observe how the model responds.

In this notebook we use `distilgpt2`, a smaller version of GPT-2. Because it was trained on a large and varied text corpus, it can often produce plausible continuations for many topics.

Try changing the prompt and compare the outputs.

# Comparing Candidate Next Words

Now we get to an interesting part: we will observe the model's ability to make a **decision** between two or more candidate next words.

This is where context matters. The model assigns a probability to each candidate continuation and we can compare those probabilities directly. By looking at these scores, you can see how the model interprets the prompt and which continuation it considers most likely.

In [ ]:
def continuation_logprob(prompt_text, continuation_text):
    full_text = prompt_text + continuation_text
    prompt_ids = tokenizer(prompt_text, return_tensors="pt")["input_ids"][0].to(device)
    full_ids = tokenizer(full_text, return_tensors="pt")["input_ids"][0].to(device)

    with torch.no_grad():
        out = model(full_ids.unsqueeze(0))
        log_probs = torch.log_softmax(out.logits[0], dim=-1)

    start = len(prompt_ids)
    total = 0.0

    for pos in range(start, len(full_ids)):
        prev_pos = pos - 1
        token_id = full_ids[pos].item()
        total += log_probs[prev_pos, token_id].item()

    return total

candidates = [
    " moustache",
    " beard",
    " hat",
    " neck",
]

scores = []
for cand in candidates:
    score = continuation_logprob(prompt, cand)
    scores.append(score)

scores_tensor = torch.tensor(scores)
cand_probs = torch.softmax(scores_tensor, dim=0)

print("Candidate comparison for the same prompt:")
for cand, score, prob in zip(candidates, scores, cand_probs.tolist()):
    print(f"{cand!r:<14} logprob={score:.3f}   relative_prob={prob:.3f}")

`logprob` (log probability) is the natural logarithm of probability. We use log probabilities because they are numerically stable when probabilities are very small.

In language modeling, sequence probabilities are products of many token probabilities. In log space, multiplication becomes addition, which is easier and more stable:

\[
\log(p_1 p_2 \cdots p_n) = \log p_1 + \log p_2 + \cdots + \log p_n
\]

Use this section to experiment with prompts and compare candidate continuations by their log probabilities. When log probabilities are close, the model is less certain. When one candidate has a much higher log probability, the model is more confident.

This uncertainty is one reason models can make mistakes or hallucinate, especially on ambiguous or low-information prompts.

# Inspecting Token Probabilities

Now we enter the land of statistics and probabilities. Here we inspect a histogram of top token predictions and their probabilities.

This gives a visual demonstration of how a model "chooses" the next word based on probability mass across candidate tokens. By looking at the histogram, you can see which tokens are considered more likely and how sharp or flat the distribution is.

In [ ]:
labels = [tokenizer.decode([tid]) for tid in top_ids.tolist()]
values = top_probs.detach().cpu().tolist()

plt.figure(figsize=(10, 4))
bars = plt.bar(range(len(values)), values, color="steelblue")
plt.xticks(range(len(values)), labels, rotation=30, ha="right")
plt.ylabel("Probability")
plt.title("Top next-token probabilities")
plt.tight_layout()
plt.show()

A model's "confidence" in its next-token prediction is reflected by the probability distribution.

- If probabilities are close together, the model is less certain.
- If one token has much higher probability, the model is more certain.

By inspecting these probabilities, you can better understand how the model handles uncertainty and why outputs can vary across prompts.

## 7. Demonstrate Context Sensitivity

A language model is highly sensitive to context.
If we slightly change the prompt, the next-token preferences also change.

In [ ]:
prompts = [
    "The cat sat on the",
    "The cat sat under the",
]

for text in prompts:
    enc = tokenizer(text, return_tensors="pt")
    enc = {k: v.to(device) for k, v in enc.items()}

    with torch.no_grad():
        out = model(**enc)
        probs = torch.softmax(out.logits[0, -1, :], dim=-1)
        top_p, top_i = torch.topk(probs, k=5)

    print("=" * 70)
    print("Prompt:", text)
    print("Top predictions:")
    for rank, (tid, prob) in enumerate(zip(top_i.tolist(), top_p.tolist()), start=1):
        print(f"{rank:>2}. {tokenizer.decode([tid])!r:<16} prob={prob:.4f}")

Here we observe the influence of the word "under" on the model's next-token predictions.

A single preposition can change the model's expectations for what should come next. This demonstrates how strongly context affects language-model behavior.

# 8. N-gram Analysis

Here is a small handmade mini language-model table, so you can show the idea behind next-word prediction without extra training.

In [ ]:
import random

manual_table = {
    ("Hij",): {"was": 0.7, "had": 0.2, "zag": 0.1},
    ("was",): {"een": 0.8, "de": 0.2},
    ("een",): {"grote": 0.5, "kleine": 0.3, "vriendelijke": 0.2},
    ("grote",): {"man": 0.7, "snor": 0.3},
    ("man",): {"met": 0.8, "en": 0.2},
    ("met",): {"een": 0.9, "zijn": 0.1},
    ("een", "grote"): {"man": 0.7, "snor": 0.3},
}

def next_word_distribution(history):
    key = tuple(history[-1:])
    if key in manual_table:
        return manual_table[key]
    return {"<eos>": 1.0}

def sample_from_distribution(dist):
    words = list(dist.keys())
    probs = list(dist.values())
    return random.choices(words, weights=probs, k=1)[0]

def manual_generate(start_words, max_steps=8):
    words = list(start_words)
    for _ in range(max_steps):
        dist = next_word_distribution(words)
        nxt = sample_from_distribution(dist)
        if nxt == "<eos>":
            break
        words.append(nxt)
    return " ".join(words)

history = ["Hij"]
dist = next_word_distribution(history)

print("History:", history)
print("Next-word distribution:")
for word, prob in dist.items():
    print(f"{word:<12} {prob:.2f}")

print()
print("Three sample continuations:")
for _ in range(3):
    print("-", manual_generate(["Hij"], max_steps=6))